"""Add professional fields to User model

Revision ID: e54fed43482a
Revises: 
Create Date: 2025-09-03 19:05:05.311495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54fed43482a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon_usage', schema=None) as batch_op:
        batch_op.alter_column('used_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('usage_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('valid_from',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock_quantity')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tax_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('billing_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=500), nullable=True))
        batch_op.alter_column('email_notifications',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_notifications',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('billing_address')
        batch_op.drop_column('tax_id')
        batch_op.drop_column('company_name')
        batch_op.drop_column('country')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('phone')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.INTEGER(), server_default=sa.text('0'), nullable=True))

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('valid_from',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('usage_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('coupon_usage', schema=None) as batch_op:
        batch_op.alter_column('used_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
